const Nationality = {
    아프가니스탄: "Afghanistan",
    알바니아: "Albania",
    알제리: "Algeria",
    안도라: "Andorra",
    앙골라: "Angola",
    "앤티가 바부다": "Antigua and Barbuda",
    아르헨티나: "Argentina",
    아르메니아: "Armenia",
    호주: "Australia",
    오스트리아: "Austria",
    아제르바이잔: "Azerbaijan",
    바베이도스: "Barbados",
    벨라루스: "Belarus",
    벨기에: "Belgium",
    베냉: "Benin",
    버뮤다: "Bermuda",
    볼리비아: "Bolivia",
    "보스니아 헤르체고비나": "Bosnia and Herzegovina",
    브라질: "Brazil",
    불가리아: "Bulgaria",
    부르키나파소: "Burkina Faso",
    부룬디: "Burundi",
    카메룬: "Cameroon",
    캐나다: "Canada",
    카보베르데: "Cape Verde Islands",
    중앙아프리카공화국: "Central African Republic",
    차드: "Chad",
    칠레: "Chile",
    중국: "China PR",
    대만: "Chinese Taipei",
    콜롬비아: "Colombia",
    코모로: "Comoros",
    콩고: "Congo",
    콩고민주공화국: "Congo DR",
    코스타리카: "Costa Rica",
    코트디부아르: "Cote d'Ivoire",
    크로아티아: "Croatia",
    쿠바: "Cuba",
    퀴라소: "Curacao",
    키프로스: "Cyprus",
    체코: "Czech Republic",
    덴마크: "Denmark",
    도미니카공화국: "Dominican Republic",
    에콰도르: "Ecuador",
    이집트: "Egypt",
    엘살바도르: "El Salvador",
    잉글랜드: "England",
    "적도 기니": "Equatorial Guinea",
    에스토니아: "Estonia",
    에티오피아: "Ethiopia",
    "페로 제도": "Faroe Islands",
    피지: "Fiji",
    핀란드: "Finland",
    프랑스: "France",
    가봉: "Gabon",
    감비아: "Gambia",
    조지아: "Georgia",
    독일: "Germany",
    가나: "Ghana",
    지브롤터: "Gibraltar",
    그리스: "Greece",
    그레나다: "Grenada",
    괌: "Guam",
    과테말라: "Guatemala",
    기니: "Guinea",
    기니비사우: "Guinea Bissau",
    가이아나: "Guyana",
    아이티: "Haiti",
    온두라스: "Honduras",
    홍콩: "Hong Kong",
    헝가리: "Hungary",
    아이슬란드: "Iceland",
    인도: "India",
    인도네시아: "Indonesia",
    이란: "Iran",
    이라크: "Iraq",
    이스라엘: "Israel",
    이탈리아: "Italy",
    자메이카: "Jamaica",
    일본: "Japan",
    요르단: "Jordan",
    카자흐스탄: "Kazakhstan",
    케냐: "Kenya",
    북한: "Korea DPR",
    대한민국: "Korea Republic",
    코소보: "Kosovo",
    라트비아: "Latvia",
    레바논: "Lebanon",
    라이베리아: "Liberia",
    리비아: "Libya",
    리히텐슈타인: "Liechtenstein",
    리투아니아: "Lithuania",
    룩셈부르크: "Luxembourg",
    마다가스카르: "Madagascar",
    말리: "Mali",
    몰타: "Malta",
    모리타니: "Mauritania",
    모리셔스: "Mauritius",
    멕시코: "Mexico",
    몰도바: "Moldova",
    몬테네그로: "Montenegro",
    몬트세라트: "Montserrat",
    모로코: "Morocco",
    모잠비크: "Mozambique",
    나미비아: "Namibia",
    네덜란드: "Netherlands",
    뉴질랜드: "New Zealand",
    나이지리아: "Nigeria",
    북마케도니아: "North Macedonia",
    북아일랜드: "Northern Ireland",
    노르웨이: "Norway",
    팔레스타인: "Palestine",
    파나마: "Panama",
    파푸아뉴기니: "Papua New Guinea",
    파라과이: "Paraguay",
    페루: "Peru",
    필리핀: "Philippines",
    폴란드: "Poland",
    포르투갈: "Portugal",
    푸에르토리코: "Puerto Rico",
    카타르: "Qatar",
    아일랜드: "Republic of Ireland",
    루마니아: "Romania",
    러시아: "Russia",
    "세인트키츠 네비스": "Saint Kitts and Nevis",
    세인트루시아: "Saint Lucia",
    "상투메 프린시페": "Sao Tome e Principe",
    사우디아라비아: "Saudi Arabia",
    스코틀랜드: "Scotland",
    세네갈: "Senegal",
    세르비아: "Serbia",
    시에라리온: "Sierra Leone",
    싱가포르: "Singapore",
    슬로바키아: "Slovakia",
    슬로베니아: "Slovenia",
    남아프리카공화국: "South Africa",
    남수단: "South Sudan",
    스페인: "Spain",
    수단: "Sudan",
    수리남: "Suriname",
    스웨덴: "Sweden",
    스위스: "Switzerland",
    시리아: "Syria",
    탄자니아: "Tanzania",
    태국: "Thailand",
    토고: "Togo",
    "트리니다드 토바고": "Trinidad and Tobago",
    튀니지: "Tunisia",
    튀르키예: "Turkey",
    우간다: "Uganda",
    우크라이나: "Ukraine",
    아랍에미리트: "United Arab Emirates",
    미국: "United States",
    우루과이: "Uruguay",
    우즈베키스탄: "Uzbekistan",
    베네수엘라: "Venezuela",
    베트남: "Vietnam",
    웨일스: "Wales",
    잠비아: "Zambia",
    짐바브웨: "Zimbabwe",
};

export default Nationality;
